# Generated by Django 4.2 on 2023-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtestProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard', models.BigIntegerField()),
                ('switch', models.BigIntegerField()),
                ('keycup', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.CharField(max_length=200)),
                ('keycup', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switchP', models.CharField(max_length=200)),
                ('keycupP', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=300)),
                ('localRangeAllProduct', models.BigIntegerField()),
                ('registry', models.DateField()),
            ],
        ),
    ]
